const data=[
    [
        {"name":"Samairaa","age":19,"marks":99,"subject":"backend"},
        {"name":"Ishika","age":18,"marks":100,"subject":"frontend"},
        {"name":"harmeet","age":28,"marks":88,"subject":"BEE"},
        {"name":"Hunar","age":38,"marks":77,"subject":"FEE"},
        {"name":"Himanshu","age":48,"marks":66,"subject":"hindi"},
    ],
    [
        {"name":"Samairaa","age":19,"marks":99,"subject":"backend"},
        {"name":"Ishika","age":18,"marks":100,"subject":"frontend"},
        {"name":"harmeet","age":28,"marks":88,"subject":"BEE"},
        {"name":"Hunar","age":38,"marks":77,"subject":"FEE"},
        {"name":"Himanshu","age":48,"marks":66,"subject":"hindi"},
    ],
    [
        {"name":"Samairaa","age":56,"subject":"FEE","rating":5},
        {"name":"Ishika","age":46,"subject":"BEE","rating":4},
        {"name":"harmeet","age":36,"subject":"backend","rating":3},
        {"name":"Hunar","age":26,"subject":"DBMS","rating":2},
        {"name":"Himanshu","age":66,"subject":"CN","rating":1},
    ]
]